# Generated by Django 5.2.5 on 2025-08-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('gabah', 'Gabah'), ('beras', 'Beras')], default='gabah', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrediksiUmurSimpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kadar_air', models.FloatField(help_text='Dalam persen, misal 12.5')),
                ('suhu', models.FloatField(help_text='Suhu (°C)')),
                ('kelembapan', models.FloatField(help_text='RH (%)')),
                ('umur_hari', models.IntegerField()),
                ('aw', models.FloatField()),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediksi', to='umur_simpan.produk')),
            ],
        ),
    ]
