# Generated by Django 5.2.5 on 2025-08-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTikus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.CharField(max_length=200)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
