# Generated by Django 5.2.5 on 2025-08-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengendali', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonfigurasiPengendali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_manual', models.BooleanField(default=False)),
                ('kipas_manual', models.BooleanField(default=False)),
                ('mode_otomatis', models.BooleanField(default=False)),
                ('suhu_min', models.FloatField(default=25.0)),
                ('suhu_max', models.FloatField(default=30.0)),
                ('kelembapan_min', models.FloatField(default=50.0)),
                ('kelembapan_max', models.FloatField(default=70.0)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
